# Generated by Django 4.2 on 2023-04-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('itemSought', models.CharField(max_length=64)),
                ('bidAmount', models.PositiveIntegerField()),
                ('postedTime', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('commentBody', models.TextField()),
                ('postedTime', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=64)),
                ('postedTime', models.DateField(auto_now_add=True)),
                ('startingBid', models.PositiveIntegerField()),
                ('imageURL', models.URLField(max_length=300)),
            ],
        ),
    ]
