# Generated by Django 4.2 on 2023-04-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageURL',
            field=models.URLField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fcoyote.ca%2Fwp%2F2013-09-17%2Fthe-power-of-the-generic-brand%2F&psig=AOvVaw2uvbkinIhdNa86IGa8Mte-&ust=1681070865740000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCMjOl5CLm_4CFQAAAAAdAAAAABAE', max_length=300),
        ),
    ]
