# Generated by Django 4.2 on 2023-04-10 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='itemSought',
            new_name='listingID',
        ),
    ]
